default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('PG_HOSTNAME', 'localhost') %>
  username: <%= ENV['PG_USR'] %>
  password: <%= ENV['PG_PWD'] %>
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: service_development

test:
  <<: *default
  database: service_test

production:
  <<: *default
  database: service_production
  url:  <%= ENV["DATABASE_URL"] %>